FROM jenkins/jenkins

USER root

RUN apt-get update -y \
    && apt-get install -y nano curl php \
    && apt-get install -y php php-mbstring php-gd php-mysql php-mysqli php-zip php-xml \
    && apt-get clean \
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update -qq \
    && apt-get install -qqy apt-transport-https ca-certificates gnupg2 software-properties-common 

RUN curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add - \
    && add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" \
    && apt-get update -qq \
    && apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y \
    && usermod -aG docker jenkins
