version: "3.8"
services:
  app:
    container_name: integracion-continua-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www/html
    networks:
      - lion
networks:
  lion:
    driver: bridge
