version: "3.8"
services:
  db:
    image: mysql
    container_name: integracion-continua-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - lion
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: integracion-continua-phpmyadmin
    restart: unless-stopped
    links:
      - db:db
    ports:
      - 8080:80
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - lion
volumes:
  mysql_data:
networks:
  lion:
    driver: bridge
